Knl 139
judsonjuniorr/knleads-docs pull request #2
Opened 2024-05-23 09:24 UTC by wesley-silv

2024-05-23 13:31 UTC, judsonjuniorr requested changes
@wesley-silv adicionei alguns comentarios apenas para alguns ajustes de texto para ficar mais compreensível pro usuário.

E agora que percebi também no anterior de listagem não tinha visto, a pasta ficou `campain` o correto é **campaign** tem um G

2024-05-23 13:31 UTC, judsonjuniorr commented on features/campain/creating-new-campain.mdx
> +Ao tocar no botão uma nova janela será aberta onde o usuário podera filtar etiquetas para adicionar, esse campo permite a insersão de etiquetas já existentes onde mais de uma etiqueta poderá ser util
- [ ] O poderá faltou um acento
- [ ] `filtar` faltou um R

Talvez aproveitar essa seção para falar que as etiquetas serão agrupadas no envio, ou seja o sistema irá adicionar os contatos de ambas as etiquetas mas nunca duplicando os mesmos, caso um contato exista em mais de uma adicionada

2024-05-23 13:31 UTC, judsonjuniorr commented on features/campain/creating-new-campain.mdx
> +Continuando a navegação no menu, o usuário encontrará um campo para adicionar seus contatos, toque no botão **Adicionar contato** para inserir um ou mais contatos desejados. Os contatos inseridos na
Essa parte tem um ponto importante que é bom colocarmos pq ja teve pessoas questionando.

Na janela que aparece para adicionar os contatos ele vai retornar apenas uma parte dos contatos, não todos que a pessoa tem salvo, para adicionar um contato que não está na listagem, é necessário que faça a pesquisa dele pelo nome ou número de telefone

2024-05-23 13:31 UTC, judsonjuniorr commented on features/campain/creating-new-campain.mdx
> +Ao inseir o nome da campanha o usuário deverá pressionar o botão **Continuar** para ser direcionado para o menu onde poderá montar um campanha. Realizando esta ação o usuário visualizará os campos co
- [ ] o inserir faltou um R, ficou `inseir`
- [ ] na parte "poderá montar um campanha", trocar o um por uma, por campanha ser no feminino

2024-05-23 13:31 UTC, judsonjuniorr commented on features/campain/creating-new-campain.mdx
> +No topo do menu será mostrado o nome que identificará a campanha criada pelo usuário, como por exemplo: **First campain**. Existem quatros campos os quais são destinados à inserção de **Contatos**, *
Talvez aqui trocar o quatro campos por seções, acho que faz mais sentido.
Campo me lembra o input ja uma seção são pedaços da tela

2024-05-23 13:31 UTC, judsonjuniorr commented on features/campain/creating-new-campain.mdx
> +Ao navegar no menu o usuário encontrará um campo para adicionar suas etiquetas, toque no botão **Adicionar etiqueta** para inserir a etiqueta desejada. Estas etiquetas podem ser criadas para identifi
Alterar essa parte:
`Estas etiquetas podem ser criadas para identificar detalhes da campanha como lançamentos, promoções, orçamentos e muito mais.`

Por algo assim:
Estas etiquetas podem ser criadas para segmentar seus contatos nas campanha como lançamentos, promoções, orçamentos e muito mais.

2024-05-23 13:31 UTC, judsonjuniorr commented on features/campain/creating-new-campain.mdx
Como o caminho do arquivo é a url, acho que ficaria mais facil pro pessoal acessar se o nome fosse apenas create.

no caminho ja teremos /campaing (que é referente ao escopo de campanha) e logo após o /create que é a ação
Colocando o /creating-new-campaing fica um pouco repetitivo, se cria é novo, então não tem necessidade do new, e como o escopo da campanha vai estar antes não tem a necessidade de colocar após.

2024-05-24 03:23 UTC, wesley-silv reviewed
Review was realized!

2024-05-24 12:10 UTC, judsonjuniorr requested changes

2024-05-24 12:10 UTC, judsonjuniorr commented on features/campaign/create.mdx
> +  Conforme mostrado na sessão anterior o usuário deverá seguir os passos do menu
Só alterar o `sessão` por **seção**, de resto aprovado.

2024-05-24 12:11 UTC, judsonjuniorr commented on features/campaign/create.mdx
> +  Conforme mostrado na sessão anterior o usuário deverá seguir os passos do menu
Finalizando esse ajuste pode aprovar o MR e fazer o merge para deploy ;)

2024-05-25 00:58 UTC, wesley-silv commented on features/campaign/create.mdx
> +  Conforme mostrado na sessão anterior o usuário deverá seguir os passos do menu
@judsonjuniorr, a alteração foi realizada, o código será integrado à branch principal.

2024-05-25 01:00 UTC, merged